#include<myos/kernel/Scancode.hpp>
#include <myos/kernel/key.hpp>

namespace myos {
namespace kernel {
#define CODE_SET_SIZE 256


// index represents the scan code
struct CodeSet {
    kernel_keyboard_key_Key map[CODE_SET_SIZE] = {
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {'\t', true},
            {'`',  true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {'q',  true},
            {'1',  true},
            {0,    true},
            {0,    true},
            {0,    true},
            {'z',  true},
            {'s',  true},
            {'a',  true},
            {'w',  true},
            {'2',  true},
            {0,    true},
            {0,    true},
            {'c',  true},
            {'x',  true},
            {'d',  true},
            {'e',  true},
            {'4',  true},
            {'3',  true},
            {0,    true},
            {0,    true},
            {' ',  true},
            {'v',  true},
            {'f',  true},
            {'t',  true},
            {'r',  true},
            {'5',  true},
            {0,    true},
            {0,    true},
            {'n',  true},
            {'b',  true},
            {'h',  true},
            {'g',  true},
            {'y',  true},
            {'6',  true},
            {0,    true},
            {0,    true},
            {0,    true},
            {'m',  true},
            {'j',  true},
            {'u',  true},
            {'7',  true},
            {'8',  true},
            {0,    true},
            {0,    true},
            {',',  true},
            {'k',  true},
            {'i',  true},
            {'o',  true}, //letter O
            {'0',  true}, //number zero
            {'9',  true},
            {0,    true},
            {0,    true},
            {'.',  true},
            {'/',  true},
            {'l',  true},
            {';',  true},
            {'p',  true},
            {'-',  true},
            {0,    true},
            {0,    true},
            {0,    true},
            {'\'', true},
            {0,    true},
            {'[',  true},
            {'=',  true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {'\n', true},
            {']',  true},
            {0,    true},
            {'\\', true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {'\b', true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true},
            {0,    true}
    };
};
CodeSet codeset2;
#define FLAG_BREAK 0x80
//{.keyCode = 'A', .pressed = true},
kernel_keyboard_key_Key kernel_keyboard_scanCode_toKey(uint8_t scanCode) {
    bool make;
    kernel_keyboard_key_Key key;

    if(scanCode == 29)
        _ctrl = true;
    else if(scanCode == 157)
        _ctrl = false;
    
    if(scanCode == 0xE1)
    {}
    else if(scanCode == 0xE0)
    {}
    else    //printable char
    {
        make = (scanCode & FLAG_BREAK) == 0;
        if(make)
        {
            key = codeset2.map[static_cast<int>(scanCode)];
            return key;
        }
    }

}

char kernel_keyboard_key_tochar(kernel_keyboard_key_Key key)
{
    return key.keyCode;
}



}
}


